/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package lic;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;

import javax.swing.JOptionPane;

/**
 *
 * @author sweta verma
 */
public class Loginframe extends javax.swing.JFrame {

    /**
     * Creates new form Loginframe
     */
    
    public Loginframe() {
        initComponents();
       jLabel4.setBounds(0,0,1370,500);
       //l1.setBounds(0,500,1370,500);
       jLabel2.setBounds(50,550,250,50);
       jLabel2.setForeground(Color.BLUE);
       t1.setBounds(270,550,180,50);
       jLabel3.setBounds(500,550,250,50);
       jLabel3.setForeground(Color.BLUE);
       t2.setBounds(720,550,180,50);
       jButton1.setBounds(420,630,180,50);
       jButton1.setBackground(Color.BLUE);
       jButton1.setForeground(Color.WHITE);
   
ImageIcon img=new ImageIcon(getClass().getResource("/lic/IMG_4123.jpg"));
        java.awt.Image scaleImage = img.getImage().getScaledInstance(jLabel1.getWidth(),jLabel1.getHeight(),java.awt.Image.SCALE_DEFAULT);
javax.swing.ImageIcon img1=new javax.swing.ImageIcon(scaleImage);
jLabel1.setIcon(img1);           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("UserName");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(150, 280, 180, 40);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(160, 380, 180, 42);
        getContentPane().add(t1);
        t1.setBounds(420, 290, 140, 40);
        getContentPane().add(t2);
        t2.setBounds(420, 380, 140, 40);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(440, 500, 100, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lic/mom.JPG"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mousent(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mousexit(evt);
            }
        });
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 220, 50);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 1014, 130, 80);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         String s,s1;
        s=t1.getText();
        s1=t2.getText();
        
         try
        {
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            Connection c=DriverManager.getConnection("jdbc:odbc:company");
            Statement st=c.createStatement();
            ResultSet rs=st.executeQuery("Select * from admin where UserName = '"+s+"' and Password = '"+s1+"'");
            if(rs.next())
                {
         Mainfrm m1=new Mainfrm();
         m1.setVisible(true);
         dispose();
      }
      else
      {
          JOptionPane.showMessageDialog(this,"Your Password is incorrect");
          
      }
      
                
        }
       catch(Exception e)
       {
           System.out.println(e);
       }
       
                   
        
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void mousent(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mousent
        // TODO add your handling code here:
        ImageIcon img1=new ImageIcon(getClass().getResource("/lic/LIC_Logo.jpg"));
        java.awt.Image scaleImage = img1.getImage().getScaledInstance(jLabel4.getWidth(),jLabel4.getHeight(),java.awt.Image.SCALE_DEFAULT);
javax.swing.ImageIcon img2=new javax.swing.ImageIcon(scaleImage);
jLabel4.setIcon(img2);
    }//GEN-LAST:event_mousent

    private void mousexit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mousexit
        // TODO add your handling code here:
        ImageIcon img=new ImageIcon(getClass().getResource("/lic/mom.jpg"));
        java.awt.Image scaleImage = img.getImage().getScaledInstance(jLabel4.getWidth(),jLabel4.getHeight(),java.awt.Image.SCALE_DEFAULT);
javax.swing.ImageIcon img1=new javax.swing.ImageIcon(scaleImage);
jLabel4.setIcon(img1);
    }//GEN-LAST:event_mousexit

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loginframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loginframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loginframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loginframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loginframe().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField t1;
    private javax.swing.JPasswordField t2;
    // End of variables declaration//GEN-END:variables
}
