/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package lic;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author sweta verma
 */
public class register extends javax.swing.JInternalFrame {

    /**
     * Creates new form register
     */
    public register() {
        initComponents();
        cb1.setVisible(false);
    }
    public register(String s) {
        initComponents();
        try
        {
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            Connection c=DriverManager.getConnection("jdbc:odbc:company");
            Statement st=c.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);
            ResultSet rs=st.executeQuery("Select Policyid from register");
            while(rs.next())
            {
                cb1.addItem(rs.getInt(1));
            }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        jButton1.setText(s);
        this.setTitle(s);
        jLabel1.setText(s+" "+"A Policy");
        t1.setVisible(false);
cb1.setBounds(281,84,125, 30);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        t5 = new javax.swing.JTextField();
        t6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cb1 = new javax.swing.JComboBox();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153), 2));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setText("Register a new Policy");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel1)
                .addContainerGap(114, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(34, 0, 401, 51);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Policy ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(34, 86, 78, 18);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Policy Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(34, 130, 75, 17);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Policy Duration");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(34, 180, 107, 14);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Premium");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(34, 232, 57, 17);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Total Amount");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(34, 280, 85, 17);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Final Amount");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(34, 333, 85, 17);

        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        getContentPane().add(t1);
        t1.setBounds(281, 84, 125, 20);

        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });
        getContentPane().add(t2);
        t2.setBounds(281, 129, 125, 20);
        getContentPane().add(t3);
        t3.setBounds(281, 178, 125, 20);
        getContentPane().add(t4);
        t4.setBounds(283, 231, 123, 20);
        getContentPane().add(t5);
        t5.setBounds(283, 279, 123, 20);

        t6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t6ActionPerformed(evt);
            }
        });
        getContentPane().add(t6);
        t6.setBounds(283, 332, 123, 20);

        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(68, 379, 73, 23);

        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(235, 379, 51, 23);

        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });
        getContentPane().add(cb1);
        cb1.setBounds(197, 84, 28, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2ActionPerformed

    private void t6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String s1=jButton1.getText();
        if(s1.equals("Register"))
        {
            try
            {
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            Connection c=DriverManager.getConnection("jdbc:odbc:company");
            PreparedStatement ps=c.prepareStatement("Insert into register values(?,?,?,?,?,?)");
            ps.setInt(1,Integer.parseInt(t1.getText()));
            ps.setString(2,t2.getText());
            ps.setInt(3,Integer.parseInt(t3.getText()));
            ps.setInt(4,Integer.parseInt(t4.getText()));
            ps.setInt(5,Integer.parseInt(t5.getText()));
            ps.setInt(6,Integer.parseInt(t6.getText()));
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Succesful Register", "REGISTER",JOptionPane.INFORMATION_MESSAGE);
            t1.setText("");
            t2.setText("");
        t3.setText("");
        t4.setText("");
        t5.setText("");
        t6.setText("");
        }
            catch(Exception e)
            {
                System.out.println(e);
            }
        }
        else if(s1.equals("Update"))
        {
            try
            {
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            Connection c=DriverManager.getConnection("jdbc:odbc:company");
            PreparedStatement ps=c.prepareStatement("update register set Policyname=?,Policyduration=?,Premium=?,Totalamt=?,Finalamt=? where Policyid=?");
            ps.setString(1,t2.getText());
            ps.setInt(2,Integer.parseInt(t3.getText()));
        ps.setInt(3,Integer.parseInt(t4.getText()));
        ps.setInt(4,Integer.parseInt(t5.getText()));
        ps.setInt(5,Integer.parseInt(t6.getText()));
        ps.setInt(6,(int)cb1.getSelectedItem());
        ps.executeUpdate();
        JOptionPane.showMessageDialog(this, "SuccesfulUpdate","UPDATE",JOptionPane.INFORMATION_MESSAGE);
        t2.setText("");
        t3.setText("");
        t4.setText("");
        t5.setText("");
        t6.setText("");
        
        
            }
            catch(Exception e)
            {
            System.out.println(e);    
            }
        }
        else
        {
            try
            {
                int j=cb1.getSelectedIndex();
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            Connection c=DriverManager.getConnection("jdbc:odbc:company");
            PreparedStatement ps=c.prepareStatement("Delete from register where Policyid=?");
            ps.setInt(1,(int)cb1.getSelectedItem());
            JOptionPane.showMessageDialog(this, "Succesfully Delted","DELETED",JOptionPane.INFORMATION_MESSAGE);
            
        cb1.removeItemAt(j);
            }
            catch(Exception e)
            {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
        // TODO add your handling code here:
        int i=(int)cb1.getSelectedItem();

        try
        {
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            Connection c=DriverManager.getConnection("jdbc:odbc:company");
            Statement st=c.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);
            ResultSet rs1=st.executeQuery("Select * from register where Policyid="+i);
            if(rs1.next())
            {
                t2.setText(rs1.getString(2));
                t3.setText(""+rs1.getInt(3));
                t4.setText(""+rs1.getInt(4));
                t5.setText(""+rs1.getInt(5));
                t6.setText(""+rs1.getInt(6));
            }
        }
        catch(Exception e)
        {
         System.out.println(e);   
        }
    }//GEN-LAST:event_cb1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cb1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    // End of variables declaration//GEN-END:variables
}
