/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package lic;

import javax.swing.ImageIcon;

/**
 *
 * @author sweta verma
 */
public class welcome extends javax.swing.JFrame implements Runnable {
Thread t1;
    /**
     * Creates new form welcome
     */
    public welcome() {
  initComponents();      
         ImageIcon img=new ImageIcon(getClass().getResource("/lic/IMG_2380.jpg"));
        java.awt.Image scaleImage = img.getImage().getScaledInstance(jLabel1.getWidth(),jLabel1.getHeight(),java.awt.Image.SCALE_DEFAULT);
javax.swing.ImageIcon img1=new javax.swing.ImageIcon(scaleImage);
jLabel1.setIcon(img1);

        
       t1=new Thread(this);
        t1.start();
       
        
    }
    public void run()
    {
        for(int i=0;i<=2;i++)
        {
            try
            {
                t1.sleep(40);
                i++;
               
            }
            catch(Exception e)
            {
                System.out.println(e);
            }
            if(i<3)
            {
                String s=jLabel7.getText();
                for(int j=0;j<s.length();j++)
                {
                    char ch=s.charAt(0);
                    s=s.substring(1)+ch;
                    jLabel7.setText(s);
                    try
                    {
                        t1.sleep(200);
                      }
                    catch(Exception e)
                            {
                              System.out.println(e);
                            }
                }
            
            }
        }
       
        
        
 Loginframe l3=new Loginframe();
 l3.setVisible(true);
 dispose();
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Edwardian Script ITC", 1, 70)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("Developed By:-");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 134, 496, 83);

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 2, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Chandni Sethi,1211251007");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 269, 530, 36);

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 2, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Promila Sharma,1211251029");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 340, 530, 38);

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 2, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Shweta Verma,1211251032");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 414, 530, 34);

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 2, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Surbhi Singla,1211251035");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 480, 544, 50);

        jLabel7.setFont(new java.awt.Font("BOLDfinger", 1, 41)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Welcome to Life Insurance Company");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 11, 1490, 53);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1390, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new welcome().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
